uploads = []
generated = []

[[outputs]]
id = "kOrCH1Z-JWez6I-ZO2zs8"
uri = "file://dist/supabase-schema.sql.txt"
type = "text"
title = "supabase/schema.sql (rename to .sql after download)"

[[outputs]]
id = "yVE6y31diWM_RFFvnVR4c"
uri = "file://dist/supabase-schema.tar.gz"
type = "unspecified"
title = "supabase/schema.sql (compressed)"

[[outputs]]
id = "YEuwpSFX7CxRNHymiL5sF"
uri = "file://exports/tateo-codebase.tar.gz"
type = "unspecified"
title = "Tateo & Co codebase (38 MB, excludes node_modules/.git)"
