// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboards/AtelierPremium.tsx": () => import("../components/mockups/dashboards/AtelierPremium.tsx"),
  "./components/mockups/dashboards/ListingsPhotoForward.tsx": () => import("../components/mockups/dashboards/ListingsPhotoForward.tsx"),
  "./components/mockups/dashboards/OperatorTerminal.tsx": () => import("../components/mockups/dashboards/OperatorTerminal.tsx")
};
