-- Persistent Hillsborough parcel-rate cache.
-- Safe for environments where the original cache table already exists.
create table if not exists public.hcpa_tax_cache (
  id                    bigint generated by default as identity primary key,
  address_normalized    text not null unique,
  address_display       text not null,
  pin                   text,
  folio                 text,
  tax_district          text,
  school_tax_rate       numeric(8,4) not null,
  non_school_tax_rate   numeric(8,4) not null,
  total_millage_rate    numeric(8,4) not null,
  ad_valorem_pct        numeric(10,6) not null default 0,
  non_ad_valorem_amt    integer not null default 0,
  homestead_sample      boolean not null default false,
  sample_price          integer not null default 0,
  queried_at            timestamptz not null default now(),
  expires_at            timestamptz not null
);

alter table public.hcpa_tax_cache
  add column if not exists folio text;

create index if not exists hcpa_tax_cache_expires_idx
  on public.hcpa_tax_cache(expires_at);

alter table public.hcpa_tax_cache enable row level security;

notify pgrst, 'reload schema';